=== jeffson1985/spring4me/spring4me-web/src/main/resources/org/osforce/spring4me/widget/config/xml/widget-page-0.4.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.opensourceforce.org/schema/page"
	xmlns:tns="http://www.opensourceforce.org/schema/page" elementFormDefault="qualified">
	
	<element name="page">
		<complexType>
			<sequence>
				<element name="group" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="widget" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="title" />
										<element name="description" minOccurs="0"/>
										<element name="preference" minOccurs="0" maxOccurs="1"/>
									</sequence>

									<attribute name="id" type="string" use="required" />
									<attribute name="name" type="string" use="required" />
									<attribute name="path" type="string" use="required" />
									<attribute name="cache" type="int" use="optional" />
									<attribute name="disabled" type="boolean" />
								</complexType>
							</element>
						</sequence>

						<attribute name="id" type="string" use="required" />
						<attribute name="layout" type="string" use="optional" />
						<attribute name="disabled" type="boolean" use="optional" />
					</complexType>
				</element>
			</sequence>

			<attribute name="path" type="string" />
			<attribute name="parent" type="string" />
			<attribute name="template" type="string" />
		</complexType>
	</element>	
</schema>

=== jeffson1985/spring4me/spring4me-demo/src/main/webapp/WEB-INF/pages/profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<page xmlns="http://www.hundsun.com/schema/page" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.opensourceforce.org/schema/page http://www.opensourceforce.org/schema/page/widget-page-0.4.0.xsd"
	id="profile" template="template">
	
	<group id="top-side">
		<widget id="helpWidget" name="helpWidget" path="/help">
			<title>Top Help Widget</title>
			<description>This is the top help widget!</description>
		</widget>
	</group>
	
	<group id="left-side">
		<widget id="helpWidget1" name="helpWidget" path="/help">
			<title>Left Help Widget</title>
			<description>This is the left help widget!</description>
		</widget>
		<widget id="helpWidget2" name="helpWidget" path="/help">
			<title>Left Help Widget</title>
			<description>This is another left help widget!</description>
		</widget>
	</group>
	<group id="main-body">
		<widget id="helpWidget3" name="helpWidget" path="/help">
			<title>登录成功</title>
			<description>This is login widget used for login!</description>
		</widget>
	</group>
	<group id="right-side">
		<widget id="helpWidget4" name="helpWidget" path="/help">
			<title>Right Help Widget</title>
			<description>This is the right help widget!</description>
		</widget>
		<widget id="helpWidget5" name="helpWidget" path="/help">
			<title>Right Help Widget</title>
			<description>This is another right help widget!</description>
		</widget>
	</group>
	
	<group id="bottom-side">
		<widget id="helpWidget6" name="helpWidget" path="/help">
			<title>Bottom Help Widget</title>
			<description>This is the bottom help widget!</description>
		</widget>
	</group>
</page>
